### ISSUE TITLE
Compound Rewrites

### ISSUE THREAD

**Issue by roboguy13** [ku-fpg/hermit-shell#12]
HERMIT has a notion of a "compound `Rewrite`" and we need to find a way to represent this. An example of this is the rewrite defined by `examples/concatVanishes/WW-Ass-A.hss` and used in the file `examples/concatVanishes/ConcatVanishes.hss`.

It is possible to use `apply` and `query` to turn bring them into `Shell t`, but then it cannot passed to a command.

As it stands, it isn't possible to make a `Monad` instance for `Transform` since its type parameters are phantoms. It would be possible to use a normal monad around that (from the `constrained-normal` package), but I haven't put enough thought into that to know if that would gain us anything. A `Free` monad would also be a possibility (if we also make a `Functor` instance), but I think that would be less likely to be useful in this particular case.

If we go with one of those approaches we would also need a way to turn it back into a regular `Rewrite`, which would require some modification to how the server processes things.

**Comment by ecaustin** [comment]
Composing rewrites using KURE primitives on the server-side will be trivial.

Rather than trying to mess with things on the client side, why not just modify the `Transform` type to carry a list of methods which we can sequentially apply once transmitted?

**Comment by roboguy13** [comment]
That makes sense to me. Do you think it would be a good idea to have a pattern synonym to make the transition easier? Like this:

    data Transform a b = Transforms [Value]
    pattern Transform t = Transforms [t]

It actually compiles like that with no other changes.

**Comment by ecaustin** [comment]
For long-term maintainability reasons I would say that's a pretty bad idea.

I can make the requisite changes when I do my review of the command implementations, provided that we agree that this is the right solution to our problem.

I'd like to get @andygill's opinion before we make any sweeping changes.

**Comment by andygill** [comment]
This is a classical remote monad problem. Lets work through the example. Ideally, what would the solution look like?

````
    loadAsRewrite "WWA" $ do 
       --  absH (repH x)
       unfold "absH"
       --  repH x []
       unfold "repH"
       --  x ++ []
       unfoldRuleUnsafe "++ []" 
       --  x
````

Which gives the type

````
loadAsRewrite :: String -> Rewrite ? ->  Shell ()
````

Actually, given we will have binding, a better definition might be:

````
loadAsRewrite ::  Rewrite ? ->  Shell (Rewrite ?)
````

So, why do we need to name things? Perhaps we should have a better type for `ww-result-split-static-arg`, for example.

One idea is to make `Rewrite` an Applicative, rather than  Monad.

(End Rambling)

I'd recommend writing out the ideal script, and work from there.

**Comment by Sculthorpen** [comment]
Incidentally, the WW infrastructure and examples should be re-done at some point to make use of the new lemma capabilities.  (WW should be implemented similarly to fold-fusion in the Making a Century case study.)  Once re-done, things should simplify and there shouldn't be any converting of scripts into rewrites.  (Although that is probably still useful functionality to have.)

**Comment by xich** [comment]
What Neil said.

I've documented this in detail here:

https://github.com/ku-fpg/hermit/issues/129

I am happy to tackle this when I am back online in July (it should be short work for me), but figured I'd document the issue in case someone wants to go at it before then. 

(As Neil pointed out, we'll still likely want the capability you are discussing here... just that W/W itself may no longer require it once re-implemented as a lemma library.)

**Comment by ecaustin** [comment]
To revisit this problem, the `HERMIT.API.Dictionary.KURE` module contains a number of combinators for  composing rewrites, including `(>>>)` for left-to-right composition.

Instead of:
```
loadAsRewrite "wwa" $
do unfold "absH"
   unfold "repH"
   unfoldRuleUnsafe "++ []" 
```
can't we just write `wwa = (unfold "absH" >>> ...)`, or are the curly braces in the rewrite script doing something special that isn't captured by simple composition?

In other words, since scripts are now proper Haskell modules, can we replace uses of `loadAsRewrite` with top-level definitions?

This would probably require a refactoring of `defineRewrite`, but it should only make things simpler, right?

**Comment by andygill** [comment]
The applicative functor do notation might help here. What do we want the type of unfold to be is the question. Does unfold "A" >> unfold "B" == unfold "A" >>> unfold "B".

**Comment by ecaustin** [comment]
To clarify things, here's some relevant types and definitions from our current API implementation:
```
newtype Transform a b = Transform Value
  deriving ToJSON

type Rewrite a = Transform a a

class ToJSON m => TransCat m where
    transCat :: Value -> m

instance TransCat (Transform a b) where
    transCat = Transform

(>>>) :: (TransCat m, External m) => m -> m -> m
x >>> y = transCat $ method ">>>" [toJSON x, toJSON y]

unfoldWith :: String -> Rewrite LCore
unfoldWith str = Transform $ method "unfoldWith" [toJSON str]

ex :: Rewrite LCore
ex =  unfoldWith "A" >>> unfoldWith "B"
```

Basically, as of right now, the `ex` example would be packaged up into one large JSON structure for the server to evaluate as a whole.  There is no need to worry about defining `Monad` or `Applicative` instances since the actual `Transform` data type from KURE already has those instances defined.  The client side `(>>>)` operator is just an (admittedly sloppily) overloaded method that our shell's parser translates to an operator of the same name in the `Control.Category` module.

This should work perfectly fine as long as a rewrite script doesn't bind any intermediate values.

If we get to the point where we want to load scripts like:
```
ex2 :: Rewrite LCore
ex2 = transform $ \ c v
    if isVar v then applyT (otherRewrite v) c else fail "this is a bad example"
```
then obviously we're going to have to get away from the somewhat disingenuous representation of transformations as simple JSON `Value`s.

In other words, as long as we restrict scripts to being built using exclusively methods provided by our API, we shouldn't need to worry about doing anything special on the client side.

**Comment by Sculthorpen** [comment]
The idea behind "load-as-rewrite" (which is defined in terms of "script-to-rewrite") was to take a HERMIT script and convert it to a HERMIT rewrite, where possible.  This was motivated by scripts being more useful in some situations, and rewrites in others.  Specifically,

Scripts are:
 - easier for a user to develop interactively;
 - easier to read (except in trivial cases);
 - debuggable, as the Shell allows stepping back and forth between each command in a script, whereas rewrites are atomic.

However, Rewrites are composable.  There are plenty of strategies that take rewrites as arguments.  We can do "any-td (r)" for an arbitrary rewrite "r", but not for an arbitrary script.

The "script-to-rewrite" command is quite limited however, in that it only copes with the subset of commands that can be translated to rewrites.  Thus it fails for scripts that aren't of a certain form.  See src/HERMIT/Shell/ScriptToRewrite.hs

**Comment by Sculthorpen** [comment]
Regarding the Transform Monad/Arrow instances in KURE.  For

Transform c m a b = Transform (c -> a -> m b)

The monad instance is a reader monad where the read-only environment is (c,a).
The arrow instance is a reader arrow where the read-only environment is (c).

So for "r1 >> r2" the input "a" to r1 and r2 is the same, and the output from r1 is discarded.  Whereas "r1 >>> r2" discards feeds the output from r1 as the input to r2 (and is usually what is wanted).

That's the situation in KURE at least, I realise you may want different instances at your level.

**Comment by roboguy13** [comment]
@ecaustin Are the `External` constraints necessary for the `(<+)` and `(>>>)` functions? Those instances aren't available on the client side.

**Comment by ecaustin** [comment]
@roboguy13 Nope, I was just trying to constrain their construction somewhat since the original shell only had two external values for each of them.  The better solution is probably to remove the `External` constraints and just add more externals.

**Comment by andygill** [comment]
Given Neil's summary, we should think hard about using do-notation for `( >>>)`.  The promotion, using `rewrite`,  to a monad is a distinction we should keep, because its a different monad.

**Comment by ecaustin** [comment]
To reiterate, our `Transform` values are just `newtype` wrappers to JSON `Value`s.
We're not going to be able to use `do` notation with them, `Applicative` or `Monad`, unless we change their internal representation.

As Neil pointed out, the distinction between scripts and rewrites is more than just superficial.

Rather than changing our definition of `Transform` or `(>>>)`, I think the better solution would be to develop a separate `Script` monad that gives us the capabilities we desire.

**Comment by roboguy13** [comment]
Right now, I've had success converting examples using `>>>` to combine `Rewrite`s. There's an example in `examples/evaluation/WWAssAScript` (the compound `Rewrite` is then used in `examples/evaluation/Eval.hs`).

Is this the way that it should be done, or should allow `Applicative` do-notation as well? It is possible to make an `Applicative` instance for something with a phantom type argument (a `Monad` instance isn't possible though), but I'm not sure whether or not this is something we want.

**Comment by andygill** [comment]
How do we promote to this Monad? Do we want a `Script.rewrite`, for example?

**Comment by ecaustin** [comment]
I see no issue with having methods that mirror `apply`, `query`, etc. to lift `Transform`s to the hypothetical `Script` monad, just like we do for the `Shell` monad.

**Comment by ecaustin** [comment]
Having said that and thinking about it a bit more, maybe scripts should just be `Shell` computations?  That would give us all the functionality we need/want, right?

**Comment by roboguy13** [comment]
As a side note, I've removed `load-as-rewrite` from almost all the examples, replacing the scripts with Haskell modules, `load-as-rewrite` with `import`s and using functions to allow parameterization.

The only exceptions are `examples/fib-tuple` (due to #14) and `examples/fib-tuple` (because `Crumb`s can't be used inside of a `Rewrite` currently).

**Comment by ecaustin** [comment]
For what it's worth, I really enjoyed working with scripts as @roboguy13 currently has them set up in the `fib-tuple` example.

I think the only thing that is missing functionality-wise is interactive development.  If we could find a way to pretty-print a file like `examples/fib-tuple/FibScript.hs` based on the inputs the shell has received in a session, then we should be in really good shape, IMO.

That shouldn't be hard given that we're already serializing everything to transmit from client to server in the first place.

**Comment by roboguy13** [comment]
Right now, I'm thinking of making a function `rewriteCrumb :: Crumb -> Rewrite a` such that we'd be able to write

    wwb :: Rewrite LCore
    wwb =
      etaExpand "xs"
      >>> rewriteCrumb lamBody
      >>> unfoldWith "wrap"
      >>> rewriteCrumb (caseAlt 1) >>> rewriteCrumb altRhs
        >>> unfoldWith "unwrap"
        >>> unfoldWith "f" >>> bash
      >>> fold "f"
      >>> etaReduce

Does that seem ok to everyone?

**Comment by ecaustin** [comment]
So I think there's a more general problem at hand here, which is that we want to project what is essentially a `Shell` effect into a `Rewrite`.

That strikes me as being "bad" for a number of reasons and probably points to another distinguishing feature of scripts:  scripts can have scoping effects and rewrites can't.

I would feel more comfortable with functions like `scopeWithCrumb :: Crumb -> Shell () -> Shell ()` and `scopeWithCrumbs :: [Crumb] -> Shell () -> Shell()` to make it more explicit that there is an effect that we're trying to include.

This would change the example to:
```
wwbScript :: Shell ()
wwbScript = do
  apply $ etaExpand "xs"
  scopeWithCrumb lamBody $ do 
    apply $ unfoldWith "wrap"
    scopeWithCrumbs [caseAlt 1, altRhs] $ do 
      apply $ unfoldWith "unwrap"
      apply $ unfoldWith "f" >>> bash
    apply $ fold "f"
  apply etaReduce
```

Note that `scopeWithCrumb` is defined such that its scoping effect is undone when its argument shell computation is complete, which is easy to see given that we can use `do` notation with `Shell` computations.

I think this is a much more faithful and literal translation of the existing scripts than trying to coerce them to be `Rewrite`s.

**Comment by ecaustin** [comment]
As a followup, I think it would be possible to write a parser for the existing script files to produce a computation much like the one shown above.  There would probably be many more explicit calls to operators and functions like `scope`, e.g.
```
do apply $ unfoldWith "unwrap"
   apply $ unfoldWith "f" >>> bash
``` 
would more likely be produced as:
```
(scope (apply (unfoldWith "unwrap"))) >>
(scope (apply (unfoldWith "f" >>> bash)))
```
, but I don't really see that as a problem since in this scenario the human-readable script is the one we're more likely to actually interact with.

Furthermore, if we like the idea of including these scripts directly in our `Script` modules (I for one do) then we could toss this parser to a quasi-quoter and be done with it.

For example:
```
wwa :: Shell ()
wwa = [script| ... |]

script :: Shell ()
script = do
  ...
  apply $ wwSplit "wrap" "unwrap" (wwAssAToAssC wwa)
  ...
```

Since scripts would now be constructed at compile-time we could throw in some rewrite rules to get rid of superfluous calls to `scope`, `apply`, etc. and we're left with a human-readability on the front-end and efficiency on the back-end.


Just spitballing here.

**Comment by Sculthorpen** [comment]
For info, "script-to-rewrite" converts crumbs in scripts using the KURE combinator:

pathR :: Path Crumb -> Rewrite a -> Rewrite a

(where "Path" is a synonym for the list type)

E.g.  { [ cr1, cr2 ] ; r1 } becomes "pathR [cr1, cr2] r1" 

This is analagous to Evan's suggested "scopeWithCrumb", though less general in that it only handles rewrites not arbitrary commands.

It might be helpful to keep to a matching naming scheme with any new combinators you introduce.  E.g.  you could replace the "R" by "S" whenever you lift a rewrite combinator to a Shell combinator, giving, for example, "pathS" instead of "scopeWithCrumb".

One problem is any navigation commands that ascend the tree, such as "up" and "top", as they don't have a convenient scoping behaviour (which is why I've advocated removing them in the past).

E.g.  { [ cr1 , cr2] ; r1 ; up ; r2 } needs to be expressed as "pathR [cr1,cr2] r1 >>> pathR [cr1] r2", and can't be expressed as "pathR [cr1,cr2] ( ??? )"

**Comment by ecaustin** [comment]
Following up on Neil's comment, it would seem that controlling scoping at the `Shell` level as opposed to the `Rewrite` level might let us handle `KernelEffects` in scripts a bit better?

His example `{ [ cr1 , cr2] ; r1 ; up ; r2 }` could be translated to `pathS [cr1, cr2] $ apply r1 >> performKernelEffect up >> apply r2` (I've taken his suggestion of renaming `scopeWithCrumbs` to `pathS`).

Does that eliminate some of the grievances raised against `up` and `top`?

**Comment by andygill** [comment]
Do we need `up`? I like the idea of `pathS` not supporting  `up` and `top`, beyond the scope you are in.

**Comment by Sculthorpen** [comment]
I think it may be possible to treat "top" as a synonym for "} {".

**Comment by ecaustin** [comment]
Is the current question whether we want to permit using `up` and `top` in scripts, or whether we want to permit using them at all?

Certainly both provide useful interactions in the shell in a much nicer way than their potential elaborations do.

**Comment by roboguy13** [comment]
At what point should something no longer be able to be implemented as a `Rewrite` and it needs to be a `Shell` action? Maybe we should restrict `KernelEffect`s to `Shell`s.

We can still have separated `Shell` actions in other modules, etc but we can't pass them (at the moment at least) to other commands which is a distinguishing characteristic between `Rewrite`s and `Shell`s.

In HERMIT, it looks like `script-to-rewrite` only accepts the `{` and `}` `KernelEffect`s and not others like `top`.

**Comment by roboguy13** [comment]
I'm going to close this. I implemented `pathS` and it's working for the example that uses it. I was going to suggest that later we could implement a `Monoid` instance for `Rewrite` so that we can `mconcat` a list of `Rewrite`s instead of using `(>>>)` everywhere but thinking about it some more, I don't think that `(>>>)` is associative. If that is the case, we could implement our own `rewriteScope :: [Rewrite a] -> Rewrite a` operation instead.

As it stands, `KernelEffect`s other than basic scoping cannot be used in `Rewrite`s but this reflects how HERMIT's `script-to-rewrite` functionality originally worked.

**Comment by Sculthorpen** [comment]
(>>>) is associative, and has to be as it's a law of the Category class.

However, "Rewrite a" is a synonym for "Transform a a", and KURE already provides a Monoid instance for Transform based on applying each transformation to the same input value and merging the resultant values afterwards.

instance Monoid b => Monoid (Transform a b) where ...

To get the monoidal behavour you want for Rewrites, you should use the KURE combinator:

serialise :: [Rewrite a] -> Rewrite a

(Defined in Language/KURE/Combinators/Arrow.hs, albeit with a rather more general type signature.)
